export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';

export const ROUTEN = {
  ANMELDEN: '/anmelden',
  REGISTRIEREN: '/registrieren',
  PASSWORT_VERGESSEN: '/passwort-vergessen',
  PASSWORT_ZURUECKSETZEN: '/passwort-zuruecksetzen',
  EMAIL_VERIFIZIEREN: '/email-verifizieren',
  DASHBOARD: '/dashboard',
  MITGLIEDER: '/mitglieder',
  MITARBEITER: '/mitarbeiter',
  ABTEILUNGEN: '/abteilungen',
  TEAMS: '/teams',
  KALENDER: '/kalender',
  TURNIERE: '/turniere',
  NACHRICHTEN: '/nachrichten',
  FAHRGEMEINSCHAFTEN: '/fahrgemeinschaften',
  ELTERN: '/eltern',
  WORKFLOWS: '/workflows',
  HALLEN: '/hallen',
  SCHIEDSRICHTER: '/schiedsrichter',
  BUCHHALTUNG: '/buchhaltung',
  SPONSOREN: '/sponsoren',
  FORMULARE: '/formulare',
  DOKUMENTE: '/dokumente',
  DFBNET: '/dfbnet',
  EINSTELLUNGEN: '/einstellungen',
  POSTEINGANG: '/posteingang',
} as const;
